# 'en', 'tr', 'ch'
plugin-language: 'en'
plugin-prefix: '&6[&eTDG&6]'
check-for-update: true
hover-effect: true
hooks:
  auto-detect: true
  PlaceholderAPI: false
  GroupManager: false
  LuckPerms: false
  PermissionsEx: false
  Vault: false
  BentoBox: false
  ASkyBlock: false
