# Plugin language supports 'en' for English, 'tr' for Turkish, and 'ch' for Chinese
Language: 'en'

Plugin-Prefix: '&6[&a&lTDG&6]'

# Enables icon hover effect
Hover-Effect: true

Hooks:
  PlaceholderAPI: false
  Vault: false